# Render Blueprint YAML for Node backend
services:
  - type: web
    name: mini-plant-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://greenify-frontend-chi.vercel.app
    autoDeploy: true
    rootDir: backend
